In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report



In [31]:
data = pd.read_csv(r"c:\Users\v_bha\Downloads\pca.csv")

print(data)

print(data.columns)

     compactness  circularity  distance_circularity  radius_ratio  \
0             95         48.0                  83.0         178.0   
1             91         41.0                  84.0         141.0   
2            104         50.0                 106.0         209.0   
3             93         41.0                  82.0         159.0   
4             85         44.0                  70.0         205.0   
..           ...          ...                   ...           ...   
840           93         34.0                  66.0         140.0   
841           93         39.0                  87.0         183.0   
842           89         46.0                  84.0         163.0   
843          106         54.0                 101.0         222.0   
844           86         36.0                  78.0         146.0   

     pr.axis_aspect_ratio  max.length_aspect_ratio  scatter_ratio  \
0                    72.0                       10          162.0   
1                    57.0        

In [32]:
print(data.isnull().sum())

compactness                    0
circularity                    5
distance_circularity           4
radius_ratio                   6
pr.axis_aspect_ratio           2
max.length_aspect_ratio        0
scatter_ratio                  1
elongatedness                  1
pr.axis_rectangularity         3
max.length_rectangularity      0
scaled_variance                3
scaled_variance.1              2
scaled_radius_of_gyration      2
scaled_radius_of_gyration.1    4
skewness_about                 6
skewness_about.1               1
skewness_about.2               1
hollows_ratio                  0
class                          0
dtype: int64


In [33]:
x = data.drop("class", axis=1)#this make all the clomn into this x and removes the output col

y = data["class"]

fill_missing_values = SimpleImputer(strategy = "median")

x = fill_missing_values.fit_transform(x)



In [35]:
scaler = StandardScaler()

x = scaler.fit_transform(x)


In [36]:
print(data)

     compactness  circularity  distance_circularity  radius_ratio  \
0             95         48.0                  83.0         178.0   
1             91         41.0                  84.0         141.0   
2            104         50.0                 106.0         209.0   
3             93         41.0                  82.0         159.0   
4             85         44.0                  70.0         205.0   
..           ...          ...                   ...           ...   
840           93         34.0                  66.0         140.0   
841           93         39.0                  87.0         183.0   
842           89         46.0                  84.0         163.0   
843          106         54.0                 101.0         222.0   
844           86         36.0                  78.0         146.0   

     pr.axis_aspect_ratio  max.length_aspect_ratio  scatter_ratio  \
0                    72.0                       10          162.0   
1                    57.0        

In [37]:
print(data.isnull().sum())

compactness                    0
circularity                    5
distance_circularity           4
radius_ratio                   6
pr.axis_aspect_ratio           2
max.length_aspect_ratio        0
scatter_ratio                  1
elongatedness                  1
pr.axis_rectangularity         3
max.length_rectangularity      0
scaled_variance                3
scaled_variance.1              2
scaled_radius_of_gyration      2
scaled_radius_of_gyration.1    4
skewness_about                 6
skewness_about.1               1
skewness_about.2               1
hollows_ratio                  0
class                          0
dtype: int64


In [38]:
#pca

pca_model = PCA(n_components = 0.95)


x_pca = pca_model.fit_transform(x)


In [39]:
x_train,x_test,y_train,y_test = train_test_split(x_pca,y,test_size = 0.02,random_state = 100)

In [28]:
print(x_train.shape)
print(x_train[:5])

(828, 7)
[[ 3.62490794e+00 -8.29848834e-01  9.10000000e+01 -5.09091059e-01
  -5.06278392e-02  3.91156437e-01  7.48923217e-01]
 [ 4.24514075e+00 -1.27564531e+00  6.23000000e+02 -4.18834015e-01
  -1.81885004e+00  2.46541945e-01  2.02455621e-01]
 [-5.85505609e-01 -8.86933993e-01  5.21000000e+02 -2.05189975e+00
   1.38182327e+00  5.19151412e-01 -1.93449860e-01]
 [-4.92671455e-01 -1.18689498e+00  7.28000000e+02 -3.58009455e-01
   1.48980703e-01  1.31809639e+00 -4.69754687e-01]
 [ 6.26743614e+00 -3.38914490e+00  3.49000000e+02  6.51687406e-01
  -5.81993608e-01 -2.45450439e+00 -5.99683060e-01]]


In [43]:
model = RandomForestClassifier(n_estimators = 100,criterion = "gini",max_depth = 3,min_samples_leaf = 2,min_samples_split = 5,random_state = 100,bootstrap = True,max_features = "sqrt")


model.fit(x_train,y_train)

model_predictions = model.predict(x_test)

In [ ]:
#evalution metrices

accuracy = accuracy_score(y_test,model_predictions)
print(accuracy)



cf_matrix = confusion_matrix(y_test,model_predictions)
print(cf_matrix)

classification_reports = classification_report(y_test,model_predictions)
print(classification_reports)

0.7647058823529411
[[2 2 0]
 [0 7 0]
 [1 1 4]]
              precision    recall  f1-score   support

         bus       0.67      0.50      0.57         4
         car       0.70      1.00      0.82         7
         van       1.00      0.67      0.80         6

    accuracy                           0.76        17
   macro avg       0.79      0.72      0.73        17
weighted avg       0.80      0.76      0.76        17



In [50]:
cross_score = cross_val_score(model,x,y,cv = 5,scoring = "accuracy")

print(cross_score)

print(cross_score.mean())

[0.82840237 0.88757396 0.9112426  0.82248521 0.9112426 ]
0.8721893491124261


In [ ]:
#hyper paramter tuning

paramter = {"n_estimators":[50,100,200],"criterion":["gini","entropy"],"max_depth" :[5,10,15,200],"min_samples_split": [2,5,10],"min_samples_leaf" : [2,5,10,15],"max_features" : ["sqrt","log2"],"bootstrap":[True,False]}

grid_search = RandomizedSearchCV(RandomForestClassifier(),param_distributions = paramter,cv = 5,scoring = "r2")

grid_search.fit(x_train,y_train)

print(grid_search.best_params_)

print(grid_search.best_score_)

best_model = grid_search.best_estimator_




best_model_predictions = best_model.predict(x_test)



In [56]:
#hyper paramter tuning

paramter = {"n_estimators":[50,100,200],"criterion":["gini","entropy"],"max_depth" :[5,10,15,200],"min_samples_split": [2,5,10],"min_samples_leaf" : [2,5,10,15],"max_features" : ["sqrt","log2"],"bootstrap":[True,False]}

grid_search = RandomizedSearchCV(RandomForestClassifier(),param_distributions = paramter,cv = 5,scoring = "accuracy")

grid_search.fit(x_train,y_train)

print(grid_search.best_params_)

print(grid_search.best_score_)

best_model = grid_search.best_estimator_




best_model_predictions = best_model.predict(x_test)



{'n_estimators': 100, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 15, 'criterion': 'entropy', 'bootstrap': True}
0.9046221248630888


In [58]:
#Best model evalution matrieces

#evalution metrices

accuracy = accuracy_score(y_test,best_model_predictions)
print(accuracy)



cf_matrix = confusion_matrix(y_test,best_model_predictions)
print(cf_matrix)

classification_reports = classification_report(y_test,best_model_predictions)
print(classification_reports)

0.7647058823529411
[[3 1 0]
 [2 4 1]
 [0 0 6]]
              precision    recall  f1-score   support

         bus       0.60      0.75      0.67         4
         car       0.80      0.57      0.67         7
         van       0.86      1.00      0.92         6

    accuracy                           0.76        17
   macro avg       0.75      0.77      0.75        17
weighted avg       0.77      0.76      0.76        17



In [59]:
cross_score = cross_val_score(best_model,x,y,cv = 5,scoring = "accuracy")

print(cross_score)

print(cross_score.mean())

[0.94674556 0.9704142  0.97633136 0.92899408 0.9704142 ]
0.9585798816568047
